name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: auth

    steps:
      # Шаг для клонирования кода репозитория
      - name: Checkout code
        uses: actions/checkout@v3

      # Установка JDK версии 11
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      # Сборка проекта и запуск тестов
      - name: Build and Run Tests
        run: |
          echo "🚀 Начинаем сборку проекта и запуск тестов..."
          ./gradlew build test
        continue-on-error: true

      # Парсинг результатов тестирования и генерация сводки
      - name: Parse Test Results
        if: always()
        run: |
          echo "📄 Парсинг результатов тестирования..."
          if ls build/test-results/test/*.xml 1> /dev/null 2>&1; then
            PASSED=$(grep -oP "(?<=<testsuite ).*?(?=>)" build/test-results/test/*.xml | grep -oP "(?<=tests=\")\d+" | paste -sd+ - | bc)
            FAILED=$(grep -oP "(?<=<testsuite ).*?(?=>)" build/test-results/test/*.xml | grep -oP "(?<=failures=\")\d+" | paste -sd+ - | bc)
            SKIPPED=$(grep -oP "(?<=<testsuite ).*?(?=>)" build/test-results/test/*.xml | grep -oP "(?<=skipped=\")\d+" | paste -sd+ - | bc)
            TOTAL=$((PASSED + FAILED + SKIPPED))
            echo "Результаты тестирования:"
            echo "✅ Успешных тестов: $((TOTAL - FAILED - SKIPPED))"
            echo "❌ Проваленных тестов: $FAILED"
            echo "🟡 Пропущенных тестов: $SKIPPED"
            echo "🔹 Всего тестов: $TOTAL"
            echo "📊 Результаты тестирования:" > test-results.txt
            echo "✅ Успешных тестов: $((TOTAL - FAILED - SKIPPED))" >> test-results.txt
            echo "❌ Проваленных тестов: $FAILED" >> test-results.txt
            echo "🟡 Пропущенных тестов: $SKIPPED" >> test-results.txt
            echo "🔹 Всего тестов: $TOTAL" >> test-results.txt
          else
            echo "⚠️ Результаты тестирования не найдены."
            echo "📊 Результаты тестирования:" > test-results.txt
            echo "❗️ Результаты тестирования недоступны." >> test-results.txt
          fi

      # Отправка уведомления в Telegram с результатами тестирования
      - name: Send Telegram Notification
        if: always()
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: |
          echo "📲 Отправка уведомления в Telegram..."
          if [ -z "$BOT_TOKEN" ] || [ -z "$CHAT_ID" ]; then
            echo "❌ Ошибка: BOT_TOKEN или CHAT_ID не установлены."
            exit 1
          fi

          # Извлекаем данные о коммите
          AUTHOR=$(cat commit_info.txt | grep "Автор коммита" | sed 's/Автор коммита: //')
          COMMIT_MSG=$(cat commit_info.txt | grep "Сообщение коммита" | sed 's/Сообщение коммита: //')

          # Извлекаем результаты тестов
          STATUS=$(cat test-results.txt)

          # Формируем сообщение для отправки в Telegram с реальными переносами строк
          MESSAGE="*🏗 Сборка завершена*
*👤 Автор коммита:* $AUTHOR
*💬 Сообщение коммита:* $COMMIT_MSG

*$STATUS*"

          # Отправляем сообщение в Telegram
          RESPONSE=$(curl -s -X POST https://api.telegram.org/bot$BOT_TOKEN/sendMessage \
            -d chat_id=$CHAT_ID \
            --data-urlencode text="$MESSAGE" \
            -d parse_mode="Markdown")

          if echo "$RESPONSE" | grep -q '"ok":true'; then
            echo "✅ Уведомление успешно отправлено."
          else
            echo "❌ Не удалось отправить уведомление."
            echo "Ответ от Telegram API: $RESPONSE"
            exit 1
          fi
